### ISSUE TITLE
Caused by: org.springframework.beans.FatalBeanException: Cannot load class null.

### ISSUE THREAD

**Issue by archerForzmy** [liuyangming/ByteTCC-sample#7]
Caused by: org.springframework.beans.FatalBeanException: Cannot load class null.
	at org.bytesoft.bytetcc.supports.dubbo.internal.CompensableBeanConfigValidator.validateReferenceBean(CompensableBeanConfigValidator.java:204) ~[bytetcc-supports-dubbo-0.5.3.jar:na]
	at org.bytesoft.bytetcc.supports.dubbo.internal.CompensableBeanConfigValidator.postProcessAfterInitialization(CompensableBeanConfigValidator.java:258) ~[bytetcc-supports-dubbo-0.5.3.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1703) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	... 15 common frames omitted

**Comment by archerForzmy** [comment]
问题在这个类中
[https://github.com/liuyangming/ByteTCC-sample/blob/master/dubbo-sample/sample-consumer/src/main/java/com/bytesvc/service/impl/GenericTransferServiceImpl.java](url)

如果去掉
`@com.alibaba.dubbo.config.annotation.Reference(interfaceClass = IAccountService.class, group = "x-bytetcc", filter = "bytetcc", loadbalance = "bytetcc", cluster = "failfast", retries = -1)`
就不报错了
